### ISSUE TITLE
如果hos里装的清日常要无key查怎么弄

### ISSUE THREAD

**Issue by duoshoumiao** [cc004/pcrdapi#1]

**Comment by cc004** [comment]
https://github.com/cc004/pcrdapi/blob/e7a19966292f22fbf2712897b922a4fbe79eefe5/__init__.py#L66
理论上是兼容的，除非你把他放在了奇怪的位置

**Comment by duoshoumiao** [comment]
> https://github.com/cc004/pcrdapi/blob/e7a19966292f22fbf2712897b922a4fbe79eefe5/__init__.py#L66
> 理论上是兼容的，除非你把他放在了奇怪的位置

 就跟其他插件一样放在moduls，它检查的是condig里面那个priconne里的key，是不是把它删了就可以了

**Comment by duoshoumiao** [comment]
莱宝 requested ProfileGetRequest at /profile/get_profile
不存在它服缓存
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\8070\HoshinoBot-master\hoshino\modules\autopcr\autopcr\module\modulebase.py", line 157, in do_from
    await self.do_task(client)
  File "C:\Users\Administrator\Desktop\8070\HoshinoBot-master\hoshino\modules\autopcr\autopcr\module\modules\tools.py", line 240, in do_task
    attack = await self.get_attack_team(defend)
  File "C:\Users\Administrator\Desktop\8070\HoshinoBot-master\hoshino\modules\autopcr\autopcr\module\modules\tools.py", line 326, in get_attack_team
    return await ArenaQuery.get_attack(self.available_unit, defen)
  File "C:\Users\Administrator\Desktop\8070\HoshinoBot-master\hoshino\modules\autopcr\autopcr\util\arena.py", line 207, in get_attack
    result = await self.query(defen, region)
  File "C:\Users\Administrator\Desktop\8070\HoshinoBot-master\hoshino\modules\autopcr\autopcr\util\arena.py", line 112, in query
    result = await self.do_query(units, region)
  File "C:\Users\Administrator\Desktop\8070\HoshinoBot-master\hoshino\modules\autopcr\autopcr\util\arena.py", line 137, in do_query
    raise e
  File "C:\Users\Administrator\Desktop\8070\HoshinoBot-master\hoshino\modules\autopcr\autopcr\util\arena.py", line 123, in do_query
    headers=self.__get_query_header(),
  File "C:\Users\Administrator\Desktop\8070\HoshinoBot-master\hoshino\modules\autopcr\autopcr\util\arena.py", line 41, in __get_query_header
    "authorization": self.__get_auth_key(),
  File "C:\Users\Administrator\Desktop\8070\HoshinoBot-master\hoshino\modules\autopcr\autopcr\util\arena.py", line 53, in __get_auth_key
    raise ValueError("请配置key")
ValueError: 请配置key

**Comment by duoshoumiao** [comment]
我现在删了又把key清了 又可以了。。。

**Comment by duoshoumiao** [comment]
![436c3c35e5aedf20e4bd317d2aef89d2](https://github.com/user-attachments/assets/a022bb4a-fa2f-4cd6-ad2a-2d11f13f6da0)
就像把内存条擦了又装回去一样。。。
